name = "Multiplexers"
uuid = "d8f48be2-8af9-45f0-b400-11a6372d221d"
authors = ["akels <akels14@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Sockets", "Serialization"]
